### ISSUE TITLE
Duplicate dashboard form submissions

### ISSUE THREAD

**Issue by chrisortman** [sparc-request/sparc-request#763] opened 2016-11-29 17:31 UTC
We have noticed that in some browsers duplicate services get added when using the _Admin Edit_ view

This seems to be because of the form having a data-remote=true setting _and_ because there is a jQuery handler tied to the click event. So what happens (in firefox) is that the form is submitted twice.

**Comment by wtholt** [comment] 2016-11-30 16:12
Hey Chris, I'm taking a look at this today. Thanks for bringing this to our attention.

**Comment by wtholt** [comment] 2016-11-30 16:35
I'm assuming you are referring to the Study Level Activities tab, I wasn't able to recreate using Firefox version 43.0.4. Do you know what browser version was being used?

**Comment by chrisortman** [comment] 2016-11-30 16:49
FF 45

Are you in the SPARC slack room? I have a video that shows how to repro it, I can send you the link, just don't want to put it on github

**Comment by wtholt** [comment] 2016-11-30 18:53
Yeah I'm on there, you can send me a DM. Username - wtholt

**Comment by WenjunHe1027** [comment] 2017-01-10 15:22
Since we have confirmed that it was an old bug with pre-v1.9.0 version. Please close this Git Issue at your convenience. Thank you and we appreciate your feedbacks! -Wenjun

**Closed** 2017-01-13 15:28 UTC
